// Generated by `supabase gen types typescript`. Regenerate after schema changes:
//   npm run db:types   (or the Supabase MCP `generate_typescript_types`)
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          slug: string;
          name: string;
          logo_url: string | null;
          theme: Json;
          plan: string;
          subscription_status: Database['public']['Enums']['sub_status'];
          trial_ends_at: string | null;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          created_at: string;
        };
        Insert: Partial<Database['public']['Tables']['organizations']['Row']> & { slug: string; name: string };
        Update: Partial<Database['public']['Tables']['organizations']['Row']>;
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          org_id: string;
          email: string | null;
          full_name: string | null;
          role: Database['public']['Enums']['org_role'];
          created_at: string;
        };
        Insert: { id: string; org_id: string; email?: string | null; full_name?: string | null; role?: Database['public']['Enums']['org_role'] };
        Update: Partial<Database['public']['Tables']['profiles']['Row']>;
        Relationships: [];
      };
      question_sets: {
        Row: { id: string; org_id: string; name: string; sections: Json; created_at: string; updated_at: string };
        Insert: { org_id: string; name?: string; sections?: Json };
        Update: Partial<Database['public']['Tables']['question_sets']['Row']>;
        Relationships: [];
      };
      game_sessions: {
        Row: {
          id: string;
          org_id: string;
          join_code: string;
          mode: Database['public']['Enums']['game_mode'];
          state: Database['public']['Enums']['game_state'];
          question_set_id: string | null;
          current_section: number | null;
          current_q_index: number | null;
          current_question: Json | null;
          section_intro: Json | null;
          active_team: number | null;
          is_bonus: boolean | null;
          mode_state: Json;
          broadcast: Json | null;
          session_token: string | null;
          created_at: string;
          ended_at: string | null;
        };
        Insert: { org_id: string; join_code: string } & Partial<Database['public']['Tables']['game_sessions']['Row']>;
        Update: Partial<Database['public']['Tables']['game_sessions']['Row']>;
        Relationships: [];
      };
      players: {
        Row: {
          id: string;
          session_id: string;
          org_id: string;
          auth_uid: string | null;
          name: string;
          score: number;
          answered: boolean;
          last_answer: string | null;
          last_correct: boolean | null;
          section_scores: Json;
          team: number | null;
          sp_state: string | null;
          created_at: string;
        };
        Insert: { session_id: string; org_id: string; name: string } & Partial<Database['public']['Tables']['players']['Row']>;
        Update: Partial<Database['public']['Tables']['players']['Row']>;
        Relationships: [];
      };
      round_answers: {
        Row: {
          id: number;
          session_id: string;
          org_id: string;
          player_id: string;
          q_index: number;
          choice: string;
          is_correct: boolean | null;
          answered_at: string;
        };
        Insert: { session_id: string; org_id: string; player_id: string; q_index: number; choice: string; is_correct?: boolean | null };
        Update: Partial<Database['public']['Tables']['round_answers']['Row']>;
        Relationships: [];
      };
    };
    Views: Record<never, never>;
    Functions: {
      current_org_id: { Args: Record<never, never>; Returns: string };
      create_organization: { Args: { p_name: string; p_slug: string }; Returns: string };
    };
    Enums: {
      game_mode: 'standard' | 'team' | 'speed' | 'oral';
      game_state:
        | 'lobby'
        | 'section_intro'
        | 'question_active'
        | 'time_up'
        | 'reveal'
        | 'leaderboard'
        | 'section_leaderboard'
        | 'ended';
      org_role: 'owner' | 'admin' | 'host';
      sub_status: 'trialing' | 'active' | 'past_due' | 'canceled' | 'incomplete';
    };
    CompositeTypes: Record<never, never>;
  };
};
